-- monitor = eDP-1, 1920x1200@60, 0x0, 1
-- monitor = desc:Iiyama North America PL2492H 1151171602103, 1920x1080@60, 1920x0, 1
-- monitor = desc:Acer Technologies Acer V233H LFA0W0524324, 1920x1080@60, 3840x0, 1

-- Laptop (base)
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "eDP-1",
	mode = "1920x1200@60",
	position = "0x0",
	scale = "1",
})

-- Iiyama (directly above laptop)
hl.monitor({
	output = "desc:Iiyama North America PL2492H 1151171602103",
	mode = "1920x1080@60",
	position = "0x-1080",
	scale = "1",
})

-- Acer (fully left of laptop, aligned to top row)
hl.monitor({
	output = "desc:Acer Technologies Acer V233H LFA0W0524324",
	mode = "1920x1080@60",
	position = "-1920x-1080",
	scale = "1",
})

-- BNQ BenQ (directly above laptop)
hl.monitor({
	output = "desc:BNQ BenQ GL2780 ETM9L0047204U",
	mode = "1920x1080@60",
	position = "0x-1080",
	scale = "1",
})

hl.workspace_rule({
	workspace = "1",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "2",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "3",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "4",
	monitor = "eDP-1",
})

hl.workspace_rule({
	workspace = "5",
	monitor = "eDP-1",
})

local terminal = "alacritty"
local menu = "wofi --show drun"

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 7,
	bezier = "myBezier",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 7,
	bezier = "default",
	style = "popin 80%",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 10,
	bezier = "default",
})
hl.animation({
	leaf = "borderangle",
	enabled = true,
	speed = 8,
	bezier = "default",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 7,
	bezier = "default",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 6,
	bezier = "default",
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind("SUPER + CTRL + 2", hl.dsp.focus({ monitor = "desc:Iiyama North America PL2492H 1151171602103" }))
hl.bind("SUPER + CTRL + 3", hl.dsp.focus({ monitor = "desc:Acer Technologies Acer V233H LFA0W0524324" }))

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.exec_cmd("keepassxc"))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("killall -SIGUSR1 waybar"))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))

hl.bind(
	"Print",
	hl.dsp.exec_cmd(
		'sh -c \'REGION=$(slurp) || exit; grim -g "$REGION" - | wl-copy &&  wl-paste > ~/Pictures/screenshots/Screenshot-$(date +%F_%T).png && dunstify "Screenshot of the region taken" -t 1000\''
	)
)
hl.bind(
	"SHIFT + Print",
	hl.dsp.exec_cmd(
		'grim - | wl-copy && wl-paste > ~/Pictures/screenshots/Screenshot-$(date +%F_%T).png && dunstify "Screenshot of the whole screen taken" -t 1000'
	)
)

hl.bind("CTRL + SPACE", hl.dsp.exec_cmd("dunstctl close-all"))

hl.bind("switch:Lid Switch", hl.dsp.exec_cmd("hyprlock"), { locked = true })

hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "0", action = "toggle" }))
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + S", hl.dsp.window.move({ workspace = "special" }))
hl.bind(mainMod .. " + T", hl.dsp.workspace.toggle_special(""))

hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + TAB", hl.dsp.focus({ workspace = "previous" }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + SPACE", hl.dsp.window.resize())

hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

hl.config({
	ecosystem = {
		enforce_permissions = 1,
	},
	general = {
		gaps_in = 5,
		gaps_out = 10,
		border_size = 2,
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = true,
		-- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
	},
	-- https://wiki.hypr.land/Configuring/Variables/#decoration
	decoration = {
		rounding = 0,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		-- https://wiki.hypr.land/Configuring/Variables/#blur
		blur = {
			enabled = false,
			size = 3,
			passes = 1,
			vibrancy = 0.1696,
		},
		shadow = {
			enabled = false,
		},
	},
	-- https://wiki.hypr.land/Configuring/Variables/#animations
	animations = {
		enabled = true,
	},
	dwindle = {
		--    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
		preserve_split = true, -- You probably want this
	},
	-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
	master = {
		new_status = "master",
	},
	-- https://wiki.hypr.land/Configuring/Variables/#misc
	misc = {
		force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
		-- vfr = true
	},
	--############
	--## INPUT ###
	--############
	-- https://wiki.hypr.land/Configuring/Variables/#input
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "caps:escape,compose:ralt",
		kb_rules = "",
		follow_mouse = 1,
		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			disable_while_typing = true,
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	-- See https://wiki.hypr.land/Configuring/Gestures
	-- Example per-device config
	-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
	--##################
	--## KEYBINDINGS ###
	--##################
	-- See https://wiki.hypr.land/Configuring/Keywords/
	-- bind = SUPER, 2, focusmonitor, HDMI-A-1
	-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
	-- Screenshot
	-- Ignore curent notifications
	-- bind = $mainMod, E, exec, $fileManager
	-- bind = $mainMod, P, togglesplit, # dwindle
	-- Move focus with mainMod + arrow keys
	-- Switch workspaces with mainMod + [0-9]
	-- Move active window to a workspace with mainMod + SHIFT + [0-9]
	-- Scroll through existing workspaces with mainMod + scroll
	-- Move/resize windows with mainMod + LMB/RMB and dragging
	-- Laptop multimedia keys for volume and LCD brightness
	-- bind = SUPER SHIFT, 201, exec, notify-send hello
	-- Ignore maximize requests from apps.
	-- windowrule = suppressevent maximize, class:.*
	-- Fix some dragging issues with XWayland
	-- windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
})
